name: Trillek
markdown: redcarpet
pygments: true
analytics:
    label: trillek.org
    code: UA-43144655-4
navigation:
  - label: forum
    url: http://forum.trillek.org/
  - label: wiki
    url: http://wiki.trillek.org/
  - label: blog
    url: http://blog.trillek.org/
  - label: logs
    url: http://logs.trillek.org/
irc:
    server: irc.freenode.net
    main_channel: project-trillek
links:
  - http://forum.trillek.org/
  - http://wiki.trillek.org/
  - http://blog.trillek.org/
  - http://logs.trillek.org/
  - http://www.reddit.com/r/trillek
  - https://github.com/trillek-team
  - https://groups.google.com/forum/#!forum/trillek
  - https://soundcloud.com/groups/trillek
  - https://plus.google.com/communities/105421959511147849143
