name: Trillek
markdown: redcarpet
pygments: true
analytics:
    label: trillek.org
    code: UA-43144655-4
navigation:
  - label: forum
    url: http://forum.trillek.org/
  - label: wiki
    url: http://wiki.trillek.org/
  - label: blog
    url: http://blog.trillek.org/
  - label: logs
    url: http://logs.trillek.org/
irc:
    server: irc.freenode.net
    main_channel: project-trillek
links:
  - label: Forum
    url: http://forum.trillek.org/
  - label: Wiki
    url: http://wiki.trillek.org/
  - label: Blog
    url: http://blog.trillek.org/
  - label: Logs
    url: http://logs.trillek.org/
  - label: Subreddit (/r/trillek)
    url: http://www.reddit.com/r/trillek
  - label: GitHub organisation
    url: https://github.com/trillek-team
  - label: Ohloh
    url: https://www.ohloh.net/p/trillek
  - label: Google group (mailing list)
    url: https://groups.google.com/forum/#!forum/trillek
  - label: SoundCloud group
    url: https://soundcloud.com/groups/trillek
  - label: Google+ community
    url: https://plus.google.com/communities/105421959511147849143
