name: Trillek
markdown: redcarpet
pygments: true
navigation:
  - label: forum
    url: http://forum.trillek.org/
  - label: blog
    url: http://blog.trillek.org/
  - label: wiki
    url: http://wiki.trillek.org/
irc:
    server: irc.freenode.net
    channels:
      -   - trillek
          - trillek-writers
      -   - trillek-dev
          - trillek-sound
      -   - trillek-dcpu
          - trillek-blah
      -   - trillek-art
