name: Trillek
markdown: redcarpet
pygments: true
analytics:
    label: trillek.org
    code: UA-43144655-4
navigation:
  - label: forum
    url: http://forum.trillek.org/
  - label: blog
    url: http://blog.trillek.org/
  - label: wiki
    url: http://wiki.trillek.org/
irc:
    server: irc.freenode.net
    channels:
      -   - trillek
          - trillek-writers
      -   - trillek-dev
          - trillek-sound
      -   - trillek-dcpu
          - trillek-blah
      -   - trillek-art
links:
  - http://forum.trillek.org/
  - http://wiki.trillek.org/
  - http://blog.trillek.org/
  - http://www.reddit.com/r/trillek
  - https://github.com/trillek-team
